jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Psdtg\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_KEDO:      ROLE_KEDO

    providers:
      fr3d_ldapbundle:
        id: fr3d_ldap.security.user.provider
      fos_userbundle:
          id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
                provider: fr3d_ldapbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_USER }
        - { path: ^/resetting, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_USER }